GET http://localhost:3001/api/persons
###

GET  http://localhost:3001/api/persons/5ec63c85b97b361a044c31da
###

DELETE http://localhost:3001/api/persons/5ec5371478c6f334b40f3f92

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "tester",
    "number": "123-456"
}